# Lab-1
# NumPy Exercises 



* Name: Elena Pashkova
* Student ID: n01587121

##### First Import NumPy as np

import numpy as np

##### Write a code to show array of 5 zeros 

In [6]:
import numpy as np

array_of_zeros = np.zeros(5)
print(array_of_zeros)

[0. 0. 0. 0. 0.]


##### Write a code to show an array of 5 ones

In [6]:
array_of_ones = np.ones(5)
print(array_of_ones)

[1, 1, 1, 1, 1]


##### Write a code to show integer numbers from 0 to 20

In [1]:
for i in range(20 + 1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


##### Write a code to show integer numbers from 0 to 20 with step 3

In [10]:
for i in range(0, 21, 3):
    print(i)

0
3
6
9
12
15
18


##### Write a code to show integer numbers from -50 to 20 with step 5

In [11]:
for i in range(-50, 20+1, 5):
    print(i)

-50
-45
-40
-35
-30
-25
-20
-15
-10
-5
0
5
10
15
20


##### Write a code to show max numbers from 10 to 50 

In [9]:
numbers = list(range(10, 51))
print(numbers)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


##### Write a code to show a 4x6 matrix with values ranging from 0 to 24

In [7]:
a = np.random.randint(0, 24 + 1, size=(4, 6))
print(a)

[[21  4 17 19  1  0]
 [20 13 10  7 14 24]
 [23  8 11 22 19 14]
 [16 15  4 18  1  5]]


##### Write a code to show a 3x3 identity matrix

In [8]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#####  Write a code to show a random number between 0 and 10

In [39]:
print("Random number between 0 and 10: ", np.random.randint(0, 10 + 1))

Random number between 0 and 10:  6


##### Write a code to Create the following matrix:

In [40]:
print(np.arange(0.0, 1.0, 0.01))

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]


Run the array below and answer the questions.

In [41]:
array = np.arange(0,25).reshape(5,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
array = np.arange(15, 20)
array

array([15, 16, 17, 18, 19])

In [47]:
print(19)

19


In [13]:
first_row = np.arange(15, 20)
second_row = first_row + 1
np.vstack((first_row, second_row))

array([[15, 16, 17, 18, 19],
       [16, 17, 18, 19, 20]])

Please save as pdf and submit in Lab 2 folder.