In [19]:
# n01587121
# IMPORTING
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [20]:
# Load the data
data_path = '/content/drive/MyDrive/ML/Assign07/Assign07/titanic_train.csv'
df = pd.read_csv(data_path)

In [21]:
# Drop the features "Name", "Ticket" and "Cabin".
df = df.drop(['Name', 'Ticket', 'Cabin'], axis=1)

In [23]:
# Fill NaN value with median of the ages
df['Age'] = df['Age'].fillna(df['Age'].median())

In [24]:
label_encoder_embarked = LabelEncoder()
df['Embarked'] = df['Embarked'].fillna('S')
df['Embarked'] = label_encoder_embarked.fit_transform(df['Embarked'])

In [ ]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [27]:
# Define features and target
X = df.drop('Survived', axis=1)
y = df['Survived']

In [28]:
# Check for any non-numeric columns
print("Columns with non-numeric data:")
print(X.select_dtypes(include=['object']).columns)

Columns with non-numeric data:
Index([], dtype='object')


In [29]:
# Splitting data into testing and training data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
# Apply KNN Classifier to the dataset and evaluate the model performance
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

In [32]:
cm_knn = confusion_matrix(y_test, y_pred_knn)
accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn)
recall_knn = recall_score(y_test, y_pred_knn)
f1_knn = f1_score(y_test, y_pred_knn)

print("KNN Classifier Performance:")
print(f"Confusion Matrix:\n{cm_knn}")
print(f"Accuracy: {accuracy_knn}")
print(f"Precision: {precision_knn}")
print(f"Recall: {recall_knn}")
print(f"F1-Score: {f1_knn}")

KNN Classifier Performance:
Confusion Matrix:
[[88 17]
 [44 30]]
Accuracy: 0.659217877094972
Precision: 0.6382978723404256
Recall: 0.40540540540540543
F1-Score: 0.4958677685950413


In [33]:
# Apply Naïve Baye’s and Logistic Regression Classifiers to the dataset and evaluate the model performance by calculating the Confusion Matrix and Accuracy.
nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)

cm_nb = confusion_matrix(y_test, y_pred_nb)
accuracy_nb = accuracy_score(y_test, y_pred_nb)

print("\nNaive Bayes Classifier Performance:")
print(f"Confusion Matrix:\n{cm_nb}")
print(f"Accuracy: {accuracy_nb}")


Naive Bayes Classifier Performance:
Confusion Matrix:
[[82 23]
 [17 57]]
Accuracy: 0.776536312849162


In [34]:
# Train and evaluate a Logistic Regression Classifier
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

cm_lr = confusion_matrix(y_test, y_pred_lr)
accuracy_lr = accuracy_score(y_test, y_pred_lr)

print("\nLogistic Regression Classifier Performance:")
print(f"Confusion Matrix:\n{cm_lr}")
print(f"Accuracy: {accuracy_lr}")


Logistic Regression Classifier Performance:
Confusion Matrix:
[[90 15]
 [19 55]]
Accuracy: 0.8100558659217877


**Analysis**

---



The Logistic Regression Classifier performs better than the Naive Bayes Classifier in terms of accuracy on this dataset.
The Logistic Regression Classifier has a higher true negative count (90 vs. 82) and a lower false positive count (15 vs. 23) compared to the Naive Bayes Classifier.


Both classifiers have comparable true positive counts (57 for Naive Bayes and 55 for Logistic Regression) but the Logistic Regression Classifier has a slightly higher accuracy overall.


**Conclusion**


---


Logistic Regression appears to be a better model for this dataset based on the accuracy metric, showing better performance in correctly classifying the passengers who survived and those who did not compared to the Naive Bayes Classifier.